add content
mentortechabc/play pull request #17
Opened 2021-05-28 10:02 UTC by yogahub

2021-05-31 16:32 UTC, mentortechabc requested changes
Пока рецепт не получается. Должен был получиться омлет с луком. Кажется, мы это обсуждали в чате.

2021-06-01 10:17 UTC, yogahub commented
Обновил  файл  вроде получилось  что-то похожее)

2021-06-03 13:41 UTC, mentortechabc commented
да, теперь похоже. Получилось разрешать конфликты после git merge?

2021-06-03 13:42 UTC, mentortechabc approved these changes

2021-06-04 08:04 UTC, yogahub commented
да разрешил конфликты, все получилось.... сделал два раза чтобы закрепить! Смержил в свою рабочую ветку  удалил стрелки  в тексте и запушил  уже потом новый документ  в  ветку мастер...

2021-06-08 14:36 UTC, merged