Main
mentortechabc/play pull request #24
Opened 2021-06-07 14:04 UTC by yogahub

Первое и второе задание

2021-06-08 15:33 UTC, mentortechabc requested changes

2021-06-08 15:33 UTC, mentortechabc commented on juri/python/task3.py
> +sqrt = sys.argv[1] ** (0.5)
это не работает. Можешь разобраться сам, почему?

2021-06-08 15:36 UTC, mentortechabc commented
еще не хватает задания №2

2021-06-09 09:23 UTC, yogahub commented
Написал код немного по другому  к третьему  заданию... но видимо  что-то  упускаю какой -то элемент в коде...

2021-06-09 21:03 UTC, mentortechabc commented on juri/python/task3.py
> +sqrt = sys.argv[1] ** (0.5)
Дело в том, что sys.argv - это список из строк. Каждый элемент - это строка. В том числе и sys.argv[1]
В python не нужно указывать типы, но операции над типами должны быть всегда "подходящими". 
Если ты запустишь свою прогармму по можешь увидеть сообщенгие 

    TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'float'

то есть для операции pow тип str (строка) не поддерживается. Нужно привести тип из строки в число перед тем, как вычислять pow.
    
    float(sys.argv[1]) ** 0.5

2021-06-16 16:35 UTC, mentortechabc commented
пока не собираемся доделывать. Закрываю.

2021-06-16 16:35 UTC, closed without merging