Homework/20210610 ex leopardilla
mentortechabc/play pull request #29
Opened 2021-06-17 14:23 UTC by leopardilla

Added exercises 7-4, 8-8 and 8-14

2021-06-18 12:17 UTC, mentortechabc requested changes

2021-06-18 12:17 UTC, mentortechabc commented on leop/ex_7_4.py
> +        if requested_topping != 'quit':
здесь и в условии цикла while ты проверяешь одно и то же условие. 
Можешь избавиться от одной из проверок, но оставить весь текущий функционал?

2021-06-19 14:44 UTC, leopardilla commented on leop/ex_7_4.py
> +        if requested_topping != 'quit':
добавила коммит https://github.com/mentortechabc/play/pull/29/commits/8ba4888b93adde48210cecc9c711c6fe09e1eda2

2021-06-19 21:25 UTC, mentortechabc approved these changes

2021-06-19 21:27 UTC, mentortechabc commented on leop/ex_7_4.py
> +    while active == True:
еще наверное можно сделать что-то такое:
```
while True:
    requested_topping = input(prompt)
    if  requested_topping == "quit":
        break
    else:
         message = "We added " + requested_topping + " to your pizza!"
         print(message)

print(order_is_ready)
```

2021-07-11 08:59 UTC, mentortechabc commented
closed / no activity

2021-07-11 08:59 UTC, closed without merging