Functions
mentortechabc/play pull request #40
Opened 2021-07-04 21:21 UTC by DramaTourG

add_interval с заглушками для базы данных и парсера.

2021-07-06 21:38 UTC, mentortechabc commented
@DramaTourG поменяй пожалуйста имя у себя в настройках git. ( github-user-name -> DramaTourG)

2021-07-08 18:16 UTC, mentortechabc requested changes
в остальном выглядит хорошо

2021-07-08 18:16 UTC, mentortechabc commented on calendar-admin/get_slots.py
> +            with sq.connect(':memory:') as con:
here you should use a special function from Maria's code to connect to a DB

2021-07-08 18:16 UTC, mentortechabc commented on calendar-admin/delete_interval.py
> +            with sq.connect(':memory:') as con:
here as well.

2021-07-08 18:16 UTC, mentortechabc commented on calendar-admin/get_slots.py
> +            with sq.connect(':memory:') as con:
see "create_connection"

2021-07-08 18:16 UTC, mentortechabc commented on calendar-admin/get_slots.py
> +            with sq.connect(':memory:') as con:
Чтобы использовать эту функцию, нужно как-то передать сюда путь к базе данных.
Я предлагаю добавить один параметр в 
```
parser = createParser()
```

в нем сделать дефолтное значение типа 'main_db.sqlite'.  

А в функции `get_slots` и ей поддобных использовать это значение из namespace.
Если нужно будет протестировать get_slots, можно будет просто передать namespace в котором `path_to_db == ':memory:'`

2021-07-08 18:16 UTC, mentortechabc commented on calendar-admin/get_slots.py
> +            with sq.connect(':memory:') as con:
Таким образом каждый разработчик сможет указывать свою базу, для тестирования можно использовать in-memory, для продакшна можно задать еще какую-то новую базу

2021-07-08 18:16 UTC, mentortechabc commented on calendar-admin/get_slots.py
> +            with sq.connect(':memory:') as con:
@DramaTourG  @leopardilla @cornhubius как вам такая идея?

2021-07-09 22:00 UTC, mentortechabc commented on calendar-admin/comand_line_parser.py
> +    pattern = r'^([0-9]{4}[-]?((0[13-9]|1[012])[-]?(0[1-9]|[12][0-9]|30)|(0[13578]|1[02])[-]?31|02[-]?(0[1-9]|1[0-9]|2[0-8]))|([0-9]{2}(([2468][048]|[02468][48])|[13579][26])|([13579][26]|[02468][048
Такие рег. выражения уже очень трудно читаются. Предлагаю заменить на более простое, а правильность hh, mm, ss проверить после конверсии в int.

2021-07-09 22:05 UTC, mentortechabc commented on calendar-admin/comand_line_parser.py
> +    pattern = r'^([0-9]{4}[-]?((0[13-9]|1[012])[-]?(0[1-9]|[12][0-9]|30)|(0[13578]|1[02])[-]?31|02[-]?(0[1-9]|1[0-9]|2[0-8]))|([0-9]{2}(([2468][048]|[02468][48])|[13579][26])|([13579][26]|[02468][048
Но лучше это сделать в отдельном PR

2021-07-09 22:09 UTC, mentortechabc requested changes
> Правильнее использовать функцию марии. Может получиться так, что нужно будет использовать какую-то другую базу данных (не sqlite3, а postgres). Если по программе будет разбросаны команды подключения, то их нужно будет везде заменять. Если использовать обертку (функцию Марии) то замену нужно будет провести только в одном месте.

Лучше начать использовать функцию Марии уже сейчас.
Тем более, она уже реализована и смержена в эту ветку.

В остальном - норм

2021-07-09 22:14 UTC, mentortechabc reviewed
Ну и еще было бы хорошо добавить тесты для этих функций

2021-07-10 21:11 UTC, DramaTourG commented on calendar-admin/get_slots.py
> +                print(convert_from_utc(result))
I also add get_slots week in this commit

2021-07-11 08:50 UTC, mentortechabc approved these changes

2021-07-11 11:58 UTC, merged